---
# defaults file for grafana-helper
grafana_dev:
  aws:
    region: ap-southeast-1
  api_key: 'eyJrIjoiMUxYSHptUmxxYlZsVU1JS2RMWHU0NXJTMWtSWDFqSUwiLCJuIjoiY29uZmlnZGVwbG95ZXIiLCJpZCI6MX0='
  base_url: 'http://ip-11-0-0-16.ap-southeast-1.compute.internal:3000'
grafana_test:
  aws:
    region: ap-southeast-1
  api_key: 'eyJrIjoiMlRyTHY2ZmxSbDgwM0VBM2x3b2RjODdjMXAyUVJBd08iLCJuIjoiY29uZmlnZGVwbG95ZXIiLCJpZCI6MX0='
  base_url: 'http://ip-11-0-0-145.ap-southeast-1.compute.internal:3000'
migration:
  root_dir: migrate
  wip_dir: wip

